# This is a basic workflow to help you get started with Actions

name: idea

# Controls when the action will run. 
on:
  schedule:
    - cron: "0 6 1 * ?"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - run: curl -H 'Content-Type:text/plain' https://sc.ftqq.com/SCU171159T5382a8d7779443ec427bedca5106f2be6085284f450c9.send?text=$(date +'%Y-%m')这个月刷新idea了吗
